package writer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/michael-freling/anime-metadata-db/internal/model"
)

func sampleRecord() model.Record {
	return model.Record{Series: &model.Series{
		ID:     "demon-slayer",
		Titles: model.Title{Original: "鬼滅の刃", Translations: map[string]string{"en": "Demon Slayer"}},
		Seasons: []model.Season{{
			ID:          "ds-s1",
			Number:      1,
			ReleaseYear: 2019,
		}},
	}}
}

func TestMarshalHasHeaderAndContent(t *testing.T) {
	raw, err := Marshal(sampleRecord())
	if err != nil {
		t.Fatal(err)
	}
	s := string(raw)
	if !strings.HasPrefix(s, "# Generated by") {
		t.Errorf("missing header: %q", s)
	}
	if !strings.Contains(s, "id: demon-slayer") {
		t.Errorf("missing content: %q", s)
	}
}

func TestWrite(t *testing.T) {
	dir := t.TempDir()
	if err := Write(dir, "franchises/demon-slayer.yaml", sampleRecord()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "franchises", "demon-slayer.yaml")); err != nil {
		t.Errorf("file not written: %v", err)
	}
}

func TestWriteIfChanged(t *testing.T) {
	dir := t.TempDir()
	rel := "demon-slayer.yaml"

	wrote, err := WriteIfChanged(dir, rel, sampleRecord())
	if err != nil {
		t.Fatal(err)
	}
	if !wrote {
		t.Error("first write should report a change")
	}

	wrote, err = WriteIfChanged(dir, rel, sampleRecord())
	if err != nil {
		t.Fatal(err)
	}
	if wrote {
		t.Error("identical write should be skipped")
	}

	changed := sampleRecord()
	changed.Series.Seasons[0].ReleaseYear = 2020
	wrote, err = WriteIfChanged(dir, rel, changed)
	if err != nil {
		t.Fatal(err)
	}
	if !wrote {
		t.Error("changed content should be written")
	}
}

func TestWriteError(t *testing.T) {
	// Parent path is a file, so MkdirAll fails.
	dir := t.TempDir()
	blocker := filepath.Join(dir, "blocker")
	if err := os.WriteFile(blocker, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := Write(dir, "blocker/child.yaml", sampleRecord()); err == nil {
		t.Error("expected error writing under a file")
	}
	if _, err := WriteIfChanged(dir, "blocker/child.yaml", sampleRecord()); err == nil {
		t.Error("expected error from WriteIfChanged under a file")
	}
}
