package writer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/michael-freling/anime-metadata-db/internal/model"
)

func sampleRecord() model.Record {
	return model.Record{Series: &model.Series{
		ID:     "demon-slayer",
		Titles: model.Title{Original: "鬼滅の刃", Translations: map[string]string{"en": "Demon Slayer"}},
		Seasons: []model.Season{{
			ID:          "ds-s1",
			Number:      1,
			ReleaseYear: 2019,
		}},
	}}
}

func TestMarshalHasHeaderAndContent(t *testing.T) {
	raw, err := Marshal(sampleRecord())
	if err != nil {
		t.Fatal(err)
	}
	s := string(raw)
	if !strings.HasPrefix(s, "# Generated by") {
		t.Errorf("missing header: %q", s)
	}
	if !strings.Contains(s, "id: demon-slayer") {
		t.Errorf("missing content: %q", s)
	}
}

func TestWrite(t *testing.T) {
	dir := t.TempDir()
	if err := Write(dir, "franchises/demon-slayer.yaml", sampleRecord()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "franchises", "demon-slayer.yaml")); err != nil {
		t.Errorf("file not written: %v", err)
	}
}

func TestWriteIfChanged(t *testing.T) {
	dir := t.TempDir()
	rel := "demon-slayer.yaml"

	wrote, err := WriteIfChanged(dir, rel, sampleRecord())
	if err != nil {
		t.Fatal(err)
	}
	if !wrote {
		t.Error("first write should report a change")
	}

	wrote, err = WriteIfChanged(dir, rel, sampleRecord())
	if err != nil {
		t.Fatal(err)
	}
	if wrote {
		t.Error("identical write should be skipped")
	}

	changed := sampleRecord()
	changed.Series.Seasons[0].ReleaseYear = 2020
	wrote, err = WriteIfChanged(dir, rel, changed)
	if err != nil {
		t.Fatal(err)
	}
	if !wrote {
		t.Error("changed content should be written")
	}
}

func sampleStaff() model.StaffRecord {
	return model.StaffRecord{
		Staff: []model.Staff{{
			ID:    "natsuki-hanae",
			Names: model.Title{Original: "花江夏樹", Translations: map[string]string{"en": "Natsuki Hanae"}},
		}},
	}
}

func TestMarshalStaff(t *testing.T) {
	raw, err := MarshalStaff(sampleStaff())
	if err != nil {
		t.Fatal(err)
	}
	s := string(raw)
	if !strings.HasPrefix(s, "# Generated by") || !strings.Contains(s, "id: natsuki-hanae") {
		t.Errorf("unexpected staff output:\n%s", s)
	}
}

func TestWriteStaffIfChanged(t *testing.T) {
	dir := t.TempDir()
	rel := "staff/voice-actors.yaml"
	wrote, err := WriteStaffIfChanged(dir, rel, sampleStaff())
	if err != nil || !wrote {
		t.Fatalf("first write: wrote=%v err=%v", wrote, err)
	}
	wrote, err = WriteStaffIfChanged(dir, rel, sampleStaff())
	if err != nil || wrote {
		t.Fatalf("identical write should be skipped: wrote=%v err=%v", wrote, err)
	}
}

func TestMarshalRecordWithCharacters(t *testing.T) {
	rec := sampleRecord()
	rec.Series.Characters = []model.Character{{
		ID:          "tanjiro",
		Names:       model.Title{Original: "竈門炭治郎"},
		Appearances: []model.CharacterAppearance{{SeriesID: "demon-slayer"}},
	}}
	raw, err := Marshal(rec)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "characters:") || !strings.Contains(string(raw), "id: tanjiro") {
		t.Errorf("merged record missing characters:\n%s", raw)
	}
}

func TestWriteError(t *testing.T) {
	// Parent path is a file, so MkdirAll fails.
	dir := t.TempDir()
	blocker := filepath.Join(dir, "blocker")
	if err := os.WriteFile(blocker, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := Write(dir, "blocker/child.yaml", sampleRecord()); err == nil {
		t.Error("expected error writing under a file")
	}
	if _, err := WriteIfChanged(dir, "blocker/child.yaml", sampleRecord()); err == nil {
		t.Error("expected error from WriteIfChanged under a file")
	}
}
