// Package writer renders resolved records to the generated data layer as
// deterministic, canonical YAML so that data/ diffs stay clean.
package writer

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/michael-freling/anime-metadata-db/internal/model"
)

// header is prepended to every generated file to warn against hand-editing.
const header = "# Generated by `builder build` — do not edit. Edit overrides/ instead.\n"

// Marshal renders a resolved record to canonical YAML bytes (2-space indent,
// with the generated-file header).
func Marshal(rec model.Record) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(rec); err != nil {
		return nil, fmt.Errorf("encode record: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("close encoder: %w", err)
	}
	return append([]byte(header), buf.Bytes()...), nil
}

// Write renders a resolved record and writes it to dataDir at relPath. Parent
// directories are created as needed.
func Write(dataDir, relPath string, rec model.Record) error {
	raw, err := Marshal(rec)
	if err != nil {
		return err
	}
	return writeBytes(dataDir, relPath, raw)
}

// WriteIfChanged writes the record only when its rendered bytes differ from the
// file already on disk, keeping builds incremental and data/ diffs clean. It
// reports whether the file was written.
func WriteIfChanged(dataDir, relPath string, rec model.Record) (bool, error) {
	raw, err := Marshal(rec)
	if err != nil {
		return false, err
	}
	dst := filepath.Join(dataDir, filepath.FromSlash(relPath))
	if existing, err := os.ReadFile(dst); err == nil && bytes.Equal(existing, raw) {
		return false, nil
	}
	if err := writeBytes(dataDir, relPath, raw); err != nil {
		return false, err
	}
	return true, nil
}

// writeBytes writes raw to dataDir/relPath, creating parent directories.
func writeBytes(dataDir, relPath string, raw []byte) error {
	dst := filepath.Join(dataDir, filepath.FromSlash(relPath))
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("create data dir: %w", err)
	}
	if err := os.WriteFile(dst, raw, 0o644); err != nil {
		return fmt.Errorf("write data file: %w", err)
	}
	return nil
}
